name: .NET CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Stop running app (kill by port)
      run: |
        $port=5050
        $process = Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue | Select-Object -ExpandProperty OwningProcess
        if ($process) {
            Stop-Process -Id $process -Force
            Write-Output "Stopped process using port $port"
        } else {
            Write-Output "No process running on port $port"
        }

    - name: Publish to local folder
      run: dotnet publish -c Release -o C:\deploy\app

    - name: Start application
      run: |
        $env:ASPNETCORE_URLS="http://localhost:5000"
        Start-Process dotnet "C:\deploy\app\cicddemo.dll"
