name: .NET CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Stop running app
      run: |
        taskkill /IM dotnet.exe /F || echo "No process running"

    - name: Publish to local folder
      run: dotnet publish -c Release -o C:\deploy\app

    - name: Start application
      run: |
        start dotnet C:\deploy\app\cicddemo.dll
